// Generated by CoffeeScript 1.7.1
(function() {
  var check_email, config, db, has_secure_password;

  has_secure_password = require('../user_crypto').has_secure_password;

  check_email = require('../user_crypto').check_email;

  db = require('../config/db');

  config = require('../config/global');

  exports.sessions = {
    signin: function(req, res) {
      console.log(req.session.user_id);
      if (req.session.user_id) {
        return res.render('dashboard');
      } else {
        return res.render('signin');
      }
    },
    signup: function(req, res) {
      console.log(req.session.user_id);
      if (req.session.user_id) {
        return res.render('dashboard');
      } else {
        return res.render('signup');
      }
    },
    destroy: function(req, res) {
      req.session.destroy();
      return res.redirect('/');
    },
    "new": function(req, res) {
      if (check_email(req.body.email, null)) {
        return db.q("select * from users where email = ? limit 1", [req.body.email]).then(function(user) {
          if (user && user.length > 0) {
            return has_secure_password(req.body.password, config.secret).then(function(pwd) {
              if (user[0].password === pwd.hash_key) {
                return req.session.regenerate(function(err) {
                  req.session.user_id = user[0].id;
                  return res.redirect("/");
                });
              } else {
                return res.render("signin", {
                  errors: "Auth error !"
                });
              }
            });
          } else {
            return res.render("signin", {
              errors: "Auth error !"
            });
          }
        });
      }
    }
  };

}).call(this);

//# sourceMappingURL=sessions.map
