// Generated by CoffeeScript 1.7.1
(function() {
  var check_email, config, db, has_secure_password, unique_email;

  db = require('../config/db');

  has_secure_password = require('../user_crypto').has_secure_password;

  unique_email = require('../user_crypto').unique_email;

  check_email = require('../user_crypto').check_email;

  config = require('../config/global');

  exports.user = {
    create: function(req, res) {
      if (check_email(req.body.email, req.body.email_confirm)) {
        return unique_email(req.body.email).then(function(unique) {
          if (unique) {
            return has_secure_password(req.body.password, config.secret).then(function(pwd) {
              return db.q("INSERT INTO users(email,password) VALUES(?,?)", [req.body.email, pwd.hash_key]).then(function(user) {
                return req.session.regenerate(function(err) {
                  req.session.user_id = user.insertId;
                  console.log("Start session:", req.session.user_id);
                  return res.render("dashboard", {
                    auth: true
                  });
                });
              });
            });
          } else {
            return res.render("signup", {
              erros: "This email already exist !"
            });
          }
        });
      } else {
        return res.render("signup", {
          errors: "Error email address !"
        });
      }
    }
  };

}).call(this);

//# sourceMappingURL=user.map
